name: Build Site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Site
      run: |
        gem install bundler
        gem install bundler jekyll
        bundle install
        bundle exec jekyll build
    container:
      image: ruby:2.6.4
