name: Build Site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@master
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Build Site
      run: |
        gem install bundler
        gem install bundler jekyll
        bundle install
        bundle exec jekyll build
        python --version
        pip3 install awscli --upgrade --user
        aws s3 ls
        ls -la
    container:
      image: ruby:2.6.4